### health check
GET http://localhost:8000/order-service/health_check
Accept: application/json

### create user
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "testUser",
  "password": "12345"
}

### create order (c7613267-4755-4b06-9405-ad52a99ba254)
POST http://localhost:8000/order-service/c7613267-4755-4b06-9405-ad52a99ba254/orders
Content-Type: application/json

{
  "productId": "CATALOG-001",
  "qty": "10",
  "unitPrice": "1500"
}

### get orders
GET http://localhost:8000/order-service/c7613267-4755-4b06-9405-ad52a99ba254/orders
Accept: application/json

### post source connect
POST http://127.0.0.1:8083/connectors
Content-Type: application/json

{
  "name" : "my-source-connect",
  "config" : {
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "connection.url": "jdbc:mysql://localhost:3306/msa_order",
    "connection.user": "root",
    "connection.password": "",
    "mode": "incrementing",
    "incrementing.column.name": "id",
    "table.whitelist": "msa_order.users",
    "topic.prefix": "my_topic_",
    "tasks.max": "1"
  }
}

### delete connect
DELETE http://127.0.0.1:8083/connectors/my-source-connect


### get source connect
GET http://127.0.0.1:8083/connectors/my-source-connect/status
Accept: application/json

### post sink connect
POST http://127.0.0.1:8083/connectors
Content-Type: application/json

{
  "name" : "my-sink-connect",
  "config" : {
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url": "jdbc:mysql://localhost:3306/msa_order",
    "connection.user": "root",
    "connection.password": "",
    "auto.create": "true",
    "auto.evolve": "true",
    "delete.enabled": "false",
    "tasks.max": "1",
    "topics": "my_topic_users"
  }
}

### get connect
GET http://127.0.0.1:8083/connectors
Accept: application/json
