server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mike6321/msa-with-spring-cloud.git
          username:
          password:
          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
