server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mike6321/msa-with-spring-cloud.git
          username: 
          password:
