### actuator health
GET http://localhost:8000/user-service/actuator/health
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0ZDAwZGI5Yi0zNGM0LTQzNTUtYjM0OC0zYjlhNjAxZjFlNjgiLCJleHAiOjE2NzEwNjAwMTd9.M61tGp0hjooYYFc0rfRFwb4lRm2We9wmDqNOoKderoCqJ4KbMU7eQ1118RH4OKRed_jT19fNimRA57svvdhBVQ
Accept: application/json

### actuator beans
GET http://localhost:8000/user-service/actuator/beans
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0ZDAwZGI5Yi0zNGM0LTQzNTUtYjM0OC0zYjlhNjAxZjFlNjgiLCJleHAiOjE2NzEwNjAwMTd9.M61tGp0hjooYYFc0rfRFwb4lRm2We9wmDqNOoKderoCqJ4KbMU7eQ1118RH4OKRed_jT19fNimRA57svvdhBVQ
Accept: application/json

### actuator busrefresh
POST http://localhost:8000/user-service/actuator/busrefresh
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0ZDAwZGI5Yi0zNGM0LTQzNTUtYjM0OC0zYjlhNjAxZjFlNjgiLCJleHAiOjE2NzEwNjAwMTd9.M61tGp0hjooYYFc0rfRFwb4lRm2We9wmDqNOoKderoCqJ4KbMU7eQ1118RH4OKRed_jT19fNimRA57svvdhBVQ
Accept: application/json

### actuator beans
GET http://localhost:8000/user-service/actuator/beans
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0ZDAwZGI5Yi0zNGM0LTQzNTUtYjM0OC0zYjlhNjAxZjFlNjgiLCJleHAiOjE2NzEwNjAwMTd9.M61tGp0hjooYYFc0rfRFwb4lRm2We9wmDqNOoKderoCqJ4KbMU7eQ1118RH4OKRed_jT19fNimRA57svvdhBVQ
Accept: application/json

### actuator refresh
POST http://localhost:49925/actuator/refresh
Content-Type: application/json

{
}

### create user
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "testUser",
  "password": "12345"
}

### get users
GET http://localhost:8000/user-service/users
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0ZDAwZGI5Yi0zNGM0LTQzNTUtYjM0OC0zYjlhNjAxZjFlNjgiLCJleHAiOjE2NzEwNjAwMTd9.M61tGp0hjooYYFc0rfRFwb4lRm2We9wmDqNOoKderoCqJ4KbMU7eQ1118RH4OKRed_jT19fNimRA57svvdhBVQ
Accept: application/json


### get user
GET http://localhost:8000/user-service/users/4d00db9b-34c4-4355-b348-3b9a601f1e68
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0ZDAwZGI5Yi0zNGM0LTQzNTUtYjM0OC0zYjlhNjAxZjFlNjgiLCJleHAiOjE2NzEwNjAwMTd9.M61tGp0hjooYYFc0rfRFwb4lRm2We9wmDqNOoKderoCqJ4KbMU7eQ1118RH4OKRed_jT19fNimRA57svvdhBVQ
Accept: application/json

### login
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### create order
POST http://localhost:8000/order-service/4d00db9b-34c4-4355-b348-3b9a601f1e68/orders
Content-Type: application/json

{
  "productId": "CATALOG-001",
  "qty": "10",
  "unitPrice": "1500"
}
