### health check
GET http://localhost:8000/user-service/health_check
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3NTJmN2E4OC1lZTFhLTQ2M2ItOWE0ZS1lYjg3YTZiMjU5OTYiLCJleHAiOjE2NzA0MDUxMjN9.TGstx4Mh9bOot5nXyuoxKQkp_ZOKwTFcXzFAf_RzThsh2yYcFwMwGWa_OTV-yRrO0YqXS5T8OkoxzLh6ek2J4g
Accept: application/json

### create user
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "testUser",
  "password": "12345"
}

### get users
GET http://localhost:8000/user-service/users
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3NTJmN2E4OC1lZTFhLTQ2M2ItOWE0ZS1lYjg3YTZiMjU5OTYiLCJleHAiOjE2NzA0MDUxMjN9.TGstx4Mh9bOot5nXyuoxKQkp_ZOKwTFcXzFAf_RzThsh2yYcFwMwGWa_OTV-yRrO0YqXS5T8OkoxzLh6ek2J4g
Accept: application/json


### get user
GET http://localhost:8000/user-service/users/752f7a88-ee1a-463b-9a4e-eb87a6b25996
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI3NTJmN2E4OC1lZTFhLTQ2M2ItOWE0ZS1lYjg3YTZiMjU5OTYiLCJleHAiOjE2NzA0MDUxMjN9.TGstx4Mh9bOot5nXyuoxKQkp_ZOKwTFcXzFAf_RzThsh2yYcFwMwGWa_OTV-yRrO0YqXS5T8OkoxzLh6ek2J4g
Accept: application/json

### login
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}
