### health check
GET http://localhost:54045/health_check
Accept: application/json

### create user
POST http://localhost:56507/users
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "testUser",
  "password": "12345"
}

